CREATE
    EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO
(
    ID            UUID                     NOT NULL,
    NAME          VARCHAR                  NOT NULL,
    PASS          VARCHAR                  NOT NULL,
    START_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE      TIMESTAMP WITH TIME ZONE NOT NULL,
    ROLES         JSONB                    NOT NULL,
    GRANTS        JSONB                    NOT NULL,
    VERSION       INTEGER                  NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone,
    MODIFIED_AT   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone
);

ALTER TABLE USUARIO
    ADD CONSTRAINT PK_USER UNIQUE (ID);

CREATE INDEX IF NOT EXISTS IDX_USUARIO_ID ON USUARIO (ID);
CREATE INDEX IF NOT EXISTS IDX_USUARIO_START_END_DATE ON USUARIO (START_DATE, END_DATE);

-- TO REVIEW
CREATE INDEX IDX_USER_ROLES ON USUARIO USING gin ((ROLES -> 'role_id'));
CREATE INDEX IDX_USER_GRANTS ON USUARIO USING gin ((GRANTS -> 'grant_id'));