CREATE
    EXTENSION IF NOT EXISTS "uuid-ossp";

-- TO IMPROVE
-- CREATE TYPE CERT_STATUS AS ENUM ('ACCEPTED', 'REJECTED', 'ACTIVE', 'INACTIVE');

DROP TABLE IF EXISTS CERTIFICATION;

CREATE TABLE CERTIFICATION
(
    ID                 UUID                     NOT NULL,
    CERTIFICATION_NAME VARCHAR                  NOT NULL,
    USER_ID            UUID                     NOT NULL,
    SUBSCRIPTION_ID    UUID,
    START_DATE         TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE           TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION            INTEGER                  NOT NULL,
    STATUS             VARCHAR                  NOT NULL,
    CREATED_AT         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone,
    MODIFIED_AT        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone
);

ALTER TABLE CERTIFICATION
    ADD CONSTRAINT PK_CERTIFICATION UNIQUE (ID);

CREATE INDEX IF NOT EXISTS IDX_CERTIFICATION_ID ON CERTIFICATION (ID);
CREATE INDEX IF NOT EXISTS IDX_CERTIFICATION_USER_ID ON CERTIFICATION (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CERTIFICATION_SUBSCRIPTION_ID ON CERTIFICATION (SUBSCRIPTION_ID);
CREATE INDEX IF NOT EXISTS IDX_CERTIFICATION_START_END_DATE ON CERTIFICATION (START_DATE, END_DATE);
