DROP TABLE IF EXISTS RESOURCE;

CREATE TABLE RESOURCE
(
    ID              UUID                     NOT NULL,
    RESOURCE_NAME   VARCHAR                  NOT NULL,
    USER_ID         UUID                     NOT NULL,
    SUBSCRIPTION_ID UUID                     NOT NULL,
    VERSION         INTEGER                  NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone,
    MODIFIED_AT     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone
);

ALTER TABLE RESOURCE
    ADD CONSTRAINT PK_RESOURCE UNIQUE (ID);

CREATE INDEX IF NOT EXISTS IDX_RESOURCE_ID ON RESOURCE (ID);
CREATE INDEX IF NOT EXISTS IDX_SUBSCRIPTION_ID ON RESOURCE (SUBSCRIPTION_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ID ON RESOURCE (USER_ID);

