version: '3.4'

services:
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
      POSTGRES_DB: meplatform
    networks:
      - meplatform-network
  wiremock:
    image: wiremock/wiremock:latest
    command: --port 8090
    ports:
      - "8090:8090"
    volumes:
      - ../_resources/wiremock/mappings/event/stubs:/./home/wiremock/mappings/
      - ../_resources/wiremock/mappings/event/response:/./home/wiremock/__files/
    networks:
      - meplatform-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - fever
    ports:
      - "8080:8080"
    networks:
      - meplatform-network
  meplatform-app:
    image: ms-meplatform:latest
    # build: .
    expose:
      - "8000"
    depends_on:
      - database
      - wiremock
    networks:
      - meplatform-network
networks:
  meplatform-network: {}